export const SUMMARY = "Corona Virus Summary: "
export const DISTRIBUTION = "Corona Virus Cases Distrbution: "
export const DAILY_WEEK_CONFIRMED = "Daily Corona Virus Cases: "
export const DAILY_WEEK_DEATHS = "Daily Corona Virus Cases: "
export const DAILY_TOTAL = "Total Corona Virus Cases: "
export const COUNTRY = "Corona Virus Cases by Country"