export const SUMMARY = "Summary"
export const VACCINATION = "Vaccination Percentage"
export const DAILY_CONFIRMED = "Daily Case"
export const DAILY_DEATHS = "Daily Deaths"
export const TOTAL_CONFIRMED = "Total Cases"
export const TOTAL_DEATHS = "Total Deaths"
export const COUNTRY = "Corona Virus Cases by Country"